[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = { version = "0.39.1" }
wasmtime-wasi = { version = "0.39.1" }
anyhow = "1.0.19"
